### ISSUE TITLE
Not working with Gnome 3.30

### ISSUE THREAD

**Issue by tiotrom** [krizajb/gnome_shell_volume_scroll#1]
Hi, it is not working with Gnome 3.30-

**Comment by krizajb** [comment]
Hi, I am still on Gnome `3.25.4`. Will try getting `3.30` up and running and keep you updated with the issue.

**Comment by tiotrom** [comment]
Hi, sorry I see that it works after I restarted the computer. Nice and useful extension. Thanks for replying so quick!
