### ISSUE TITLE
Volume doesn't show in bezel

### ISSUE THREAD

**Issue by nibley** [krizajb/gnome_shell_volume_scroll#2]
Steps to reproduce
- scroll in top panel

Volume changes perfectly, but the square notification that appears near the bottom of the screen while changing volume always shows a full volume bar. Before Eoan, this was working for me.

**Comment by Blackrucat** [comment]
Same problem.

**Comment by krizajb** [comment]
Will take a look at it, which distro are we talking about here?

**Comment by Blackrucat** [comment]
In my personal case Pop_os.
